const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const params=new URLSearchParams(location.search), guest=params.get('to')||params.get('guest');
const audio=$('#bgm'); let opened=false, pageIndex=0;
function hydrateImages(){document.querySelectorAll('img[data-src]').forEach(img=>{if(!img.getAttribute('src')) img.src=img.dataset.src})}
const pages=Array.from({length:7},(_,i)=>`page-${i+1}.jpg`);
if(guest){const note=$('.tap'); if(note) note.textContent=`For ${guest.trim().slice(0,60)}`;}
function openInvitation(e){if(e)e.preventDefault();if(opened)return;opened=true;const gate=$('#welcome');gate.classList.add('is-opening');document.body.classList.remove('gate-locked');document.body.classList.add('gate-open');hydrateImages();render();audio.play().catch(()=>{});setTimeout(()=>{gate.style.display='none';window.scrollTo({top:0,behavior:'instant'});$('#music').classList.toggle('playing',!audio.paused);},1350)}
$('#seal').addEventListener('click',openInvitation);$('#openInvite').addEventListener('click',openInvitation);$('#openingCard').addEventListener('click',openInvitation);$('#openingCard').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' ')openInvitation(e)});
$('#music').addEventListener('click',async()=>{if(audio.paused){try{await audio.play()}catch(_){}}else audio.pause();});audio.addEventListener('play',()=>$('#music').classList.add('playing'));audio.addEventListener('pause',()=>$('#music').classList.remove('playing'));
const target=new Date('2026-11-26T12:14:00+05:30').getTime();function countdown(){let d=Math.max(0,target-Date.now()),v={days:Math.floor(d/86400000)};d%=86400000;v.hours=Math.floor(d/3600000);d%=3600000;v.minutes=Math.floor(d/60000);d%=60000;v.seconds=Math.floor(d/1000);Object.entries(v).forEach(([k,x])=>{const el=$(`[data-unit="${k}"]`);if(el)el.textContent=String(x).padStart(2,'0')})}countdown();setInterval(countdown,1000);
let io;
function initReveal(){io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.12});$$('.reveal').forEach(x=>io.observe(x));}

function render(){if(!opened)return;const src=pages[pageIndex];$('#invitePage').src=src;$('#lightImage').src=src;$('#invitePage').alt=`Invitation page ${pageIndex+1}`;$('#pageNumber').textContent=String(pageIndex+1).padStart(2,'0');$('#progressBar').style.width=`${((pageIndex+1)/pages.length)*100}%`}
function move(n){pageIndex=(pageIndex+n+pages.length)%pages.length;render()}$('#prev').onclick=()=>move(-1);$('#next').onclick=()=>move(1);$('#pageOpen').onclick=()=>{$('#lightbox').hidden=false;document.body.classList.add('modal-open')};function close(){ $('#lightbox').hidden=true;document.body.classList.remove('modal-open')}$('#close').onclick=close;$('#lightPrev').onclick=()=>move(-1);$('#lightNext').onclick=()=>move(1);$('#lightbox').onclick=e=>{if(e.target.id==='lightbox')close()};
let startX=0;$('#pageOpen').addEventListener('touchstart',e=>startX=e.changedTouches[0].clientX,{passive:true});$('#pageOpen').addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-startX;if(Math.abs(dx)>45)move(dx<0?1:-1)},{passive:true});document.addEventListener('keydown',e=>{if(e.key==='Escape')close();if(!opened)return;if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1)});initReveal();
